# Site settings
baseurl = "/"
title = "Patricia Menéndez"
paginate = 5
buildFuture = true

enableEmoji = true
disableKinds = ["RSS"]

# Website's default description
  defaultDescription = ""
  defaultKeywords = ["STEM" , "female" , "maths" , "innovation"]

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]
  




[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/okayama1/"

[[menu.social]]
    name = "Twitter"
    title = "fab fa-twitter-square"
    url = "https://twitter.com/PM_maths"
    
[[menu.main]]
   weight = 3
   name = "About"
   title = "About"
   url = "/about/"    


  
[[menu.main]]
    weight = 1
   name = "Homeward Bound"
   title = "Homeward Bound"
   url = "/hb/"  
   
[[menu.main]]
    weight = 1
   name = "Where maths and stats can take you?!"
   title = "Where maths and stats can take you?!"
   url = "/maths_stats/"     
  
 
  
[params]
  author = "Patricia Menéndez. Powered by the Story theme for Hugo."
  twitter = "PM_maths"
  classes = [] 
 
 
 

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]
  
  
  


 